name: flutter_web_chartjs
description: A ChartJS wrapper for Flutter Web. flutter_web_chartjs use the HtmlElementView to render the ChartJS canvas as a Flutter Web widget.
version: 0.2.3
homepage: https://github.com/vramosx/flutter_web_chartjs
repository: https://github.com/vramosx/flutter_web_chartjs

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterWebChartjsPlugin
        fileName: flutter_web_chartjs.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.1+1

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"